version: "3.8"

services:
  www:
    image: "registry.app-maville.com/mintree-www"
    build:
      context: "."
      dockerfile: "Dockerfile"
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mintree-www.rule=Host(`www.mintree.app-maville.com`)"
        - "traefik.http.services.mintree-www.loadbalancer.server.port=80"
        - "traefik.http.routers.mintree-www.entrypoints=websecure"
        - "traefik.http.routers.mintree-www.tls.certresolver=myresolver"

networks:
  traefik-public:
    external: true
